---
name: Build Targets

on:
  - push
  - pull_request

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip build]')"
    name: ${{ matrix.target }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        target:
          - GZDoom
          - Raze
          - PrBoom-Plus

    steps:
      - uses: actions/checkout@v4

      - name: Build target
        run: |
          ./build.py --target ${{ matrix.target }}

      - name: Generate Xcode project
        run: |
          ./build.py --target ${{ matrix.target }} --xcode

      - name: List Build Directory
        if: always()
        shell: bash
        run: |
          git status
          ls -lR .
...
