name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: ${{ matrix.config.name }}
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "GZDoom"
          }
        - {
            name: "Raze"
          }
        - {
            name: "PrBoom-Plus"
          }

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        ./build.py --target ${{ matrix.config.name }}

    - name: List Build Directory
      if: always()
      shell: bash
      run: |
        git status
        ls -lR .
