---
name: Test Libraries

on: [push, pull_request]

jobs:
  test:
    if: "${{ !contains(github.event.head_commit.message, '[skip test]') }}"
    runs-on: "macos-12"
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          ./build.py --target=test-deps
...
