name: Test Libraries

on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: "macos-latest"
    steps:
    - uses: actions/checkout@v1

    - name: Run tests
      run: |
        # Remove SDKROOT when 11.0+ SDK will become the default one
        SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk ./build.py --target=test-deps
